# Generated by Django 5.2.7 on 2025-11-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpazilaModel',
        ),
    ]
