# Generated by Django 5.2.7 on 2025-12-02 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_app', '0002_delete_upazilamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('area_size', models.DecimalField(decimal_places=2, help_text='Total area in square feet', max_digits=8)),
                ('has_road', models.BooleanField(default=False)),
                ('has_gas', models.BooleanField(default=False)),
                ('has_documents_all_ok', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartment_app/img')),
                ('video', models.FileField(blank=True, null=True, upload_to='apartment_app/video')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_district', to='location_app.districtmodel')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_division', to='location_app.divisionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
