# Generated by Django 5.2.7 on 2025-12-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='land_app/img'),
        ),
        migrations.AlterField(
            model_name='landmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='land_app/video'),
        ),
    ]
