# Generated by Django 5.0 on 2026-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0002_alter_landmodel_image_alter_landmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmodel',
            name='land_name',
            field=models.CharField(max_length=100),
        ),
    ]
