# Generated by Django 5.0 on 2026-08-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0003_alter_landmodel_land_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='landmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='land_app/img'),
        ),
        migrations.AddField(
            model_name='landmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='land_app/img'),
        ),
        migrations.AddField(
            model_name='landmodel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='land_app/img'),
        ),
        migrations.AddField(
            model_name='landmodel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='land_app/img'),
        ),
    ]
