# Generated by Django 5.0 on 2026-05-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_address_profilemodel_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
