# Generated by Django 5.0 on 2026-05-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_profilemodel_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
