# Generated by Django 5.0 on 2026-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_profilemodel_created_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
