# Generated by Django 5.0 on 2026-05-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_otpmodel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='is_validated',
            new_name='otp_validated',
        ),
    ]
