# Generated by Django 5.0 on 2026-05-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_rename_is_validated_profilemodel_otp_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='otp',
            new_name='otp_code',
        ),
    ]
