# Generated by Django 5.0 on 2026-05-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_otpmodel_expires_at_alter_otpmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
