# Generated by Django 5.2.7 on 2025-11-16 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_app', '0002_delete_upazilamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('floor_number', models.IntegerField(help_text='Which floor the apartment is on')),
                ('area_sqft', models.DecimalField(decimal_places=2, help_text='Total area in square feet', max_digits=8)),
                ('master_bedrooms', models.PositiveIntegerField(default=1)),
                ('common_bedrooms', models.PositiveIntegerField(default=0)),
                ('living_bedrooms', models.PositiveIntegerField(default=0)),
                ('dining_rooms', models.PositiveIntegerField(default=1)),
                ('kitchens', models.PositiveIntegerField(default=1)),
                ('washrooms', models.PositiveIntegerField(default=1)),
                ('balconies', models.PositiveIntegerField(default=0)),
                ('storerooms', models.PositiveIntegerField(default=0)),
                ('servant_rooms', models.PositiveIntegerField(default=0)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_lift_access', models.BooleanField(default=True)),
                ('has_generator_backup', models.BooleanField(default=False)),
                ('has_security_guard', models.BooleanField(default=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_district', to='location_app.districtmodel')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_division', to='location_app.divisionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
