# Generated by Django 5.2.7 on 2025-11-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment_img/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='images', to='apartment_app.apartmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='apartment_vid/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='apartment_app.apartmentmodel')),
            ],
        ),
    ]
