# Generated by Django 5.2.7 on 2025-12-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_app', '0002_apartmentimagemodel_apartmentvideomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimagemodel',
            name='image',
            field=models.ImageField(upload_to='apartment_app/img'),
        ),
        migrations.AlterField(
            model_name='apartmentvideomodel',
            name='video',
            field=models.FileField(upload_to='apartment_app/video'),
        ),
    ]
