# Generated by Django 5.2.7 on 2025-12-02 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_app', '0003_alter_apartmentimagemodel_image_and_more'),
        ('location_app', '0002_delete_upazilamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentvideomodel',
            name='apartment',
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='apartment_app/video'),
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_district', to='location_app.districtmodel'),
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_division', to='location_app.divisionmodel'),
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ApartmentImageModel',
        ),
        migrations.DeleteModel(
            name='ApartmentVideoModel',
        ),
    ]
