# Generated by Django 5.2.7 on 2025-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_app', '0004_remove_apartmentvideomodel_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
