# Generated by Django 5.0 on 2026-07-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_app', '0005_apartmentmodel_owner_name_apartmentmodel_owner_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentmodel',
            old_name='living_bedrooms',
            new_name='drawing_rooms',
        ),
        migrations.RenameField(
            model_name='apartmentmodel',
            old_name='storerooms',
            new_name='store_rooms',
        ),
        migrations.RenameField(
            model_name='apartmentmodel',
            old_name='washrooms',
            new_name='wash_rooms',
        ),
    ]
