# Generated by Django 5.0 on 2026-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_app', '0006_rename_living_bedrooms_apartmentmodel_drawing_rooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentmodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_app/img'),
        ),
    ]
