# Generated by Django 5.0 on 2026-08-19 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0002_delete_upazilamodel'),
        ('rent_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('area_size', models.DecimalField(decimal_places=2, help_text='Total area in square feet', max_digits=8)),
                ('has_road', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_documents_all_ok', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='land_app/img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='land_app/img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='land_app/img')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='land_app/img')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='land_app/img')),
                ('video', models.FileField(blank=True, null=True, upload_to='land_app/video')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_district', to='location_app.districtmodel')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_division', to='location_app.divisionmodel')),
                ('rent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_type', to='rent_app.renttypemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
