# Generated by Django 5.0 on 2026-08-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_rentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentmodel',
            old_name='price',
            new_name='monthly_price',
        ),
    ]
