# Generated by Django 5.0 on 2026-08-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0003_rename_price_rentmodel_monthly_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='rent_app/img'),
        ),
        migrations.AlterField(
            model_name='rentmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rent_app/img'),
        ),
        migrations.AlterField(
            model_name='rentmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rent_app/img'),
        ),
        migrations.AlterField(
            model_name='rentmodel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='rent_app/img'),
        ),
        migrations.AlterField(
            model_name='rentmodel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='rent_app/img'),
        ),
        migrations.AlterField(
            model_name='rentmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent_app/video'),
        ),
    ]
