# Generated by Django 5.0 on 2026-08-24 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_app', '0002_delete_upazilamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='developer_app/img')),
                ('license_img', models.ImageField(blank=True, null=True, upload_to='developer_app/img')),
                ('video', models.FileField(blank=True, null=True, upload_to='developer_app/video')),
                ('area', models.ManyToManyField(related_name='developers_area', to='location_app.divisionmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
