# Generated by Django 5.0 on 2026-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developermodel',
            name='developer_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
