# Generated by Django 5.0 on 2026-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_app', '0002_alter_developermodel_developer_name'),
        ('location_app', '0002_delete_upazilamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developermodel',
            name='area',
            field=models.ManyToManyField(related_name='developers_area', to='location_app.districtmodel'),
        ),
    ]
