# Generated by Django 5.0 on 2026-08-25 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_app', '0003_alter_developermodel_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='developermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developermodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
